-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
local set = vim.keymap.set

set("n", "<leader>pv", vim.cmd.Explore, { desc = "Open the explorer" })

set("i", "jj", "<Esc>")

-- Clear highlights on search when pressing <Esc> in normal mode
--  See `:help hlsearch`
set("n", "<Esc>", "<cmd>nohlsearch<CR>")

-- Delete a buffer
set("n", "<leader>d", "<cmd>bdelete<CR>")

-- Get to the end of line - Enter, get to the begging - Tab
set("n", "<Enter>", "$")
set("n", "<Tab>", "0")

-- Dismiss Noice Message
set("n", "<Esc>", "<cmd>NoiceDismiss<CR>", { desc = "Dismiss Noice Message" })

-- When press <Esc> all lines words that are highlighted disappear
set("n", "<Esc>", "<cmd>let @/=''<CR>")

-- LazyVim's keymaps
--
-- -- better up/down
-- set({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
-- set({ "n", "x" }, "<Down>", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
-- set({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
-- set({ "n", "x" }, "<Up>", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
--
-- -- Move to window using the <ctrl> hjkl keys
-- set("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window", remap = true })
-- set("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window", remap = true })
-- set("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window", remap = true })
-- set("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window", remap = true })
--
-- -- Resize window using <ctrl> arrow keys
-- set("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase Window Height" })
-- set("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease Window Height" })
-- set("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease Window Width" })
-- set("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase Window Width" })
--
-- -- Move Lines
-- set("n", "<A-j>", "<cmd>m .+1<cr>==", { desc = "Move Down" })
-- set("n", "<A-k>", "<cmd>m .-2<cr>==", { desc = "Move Up" })
-- set("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
-- set("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
-- set("v", "<A-j>", ":m '>+1<cr>gv=gv", { desc = "Move Down" })
-- set("v", "<A-k>", ":m '<-2<cr>gv=gv", { desc = "Move Up" })
--
-- -- buffers
-- set("n", "<S-h>", "<cmd>bprevious<cr>", { desc = "Prev Buffer" })
-- set("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next Buffer" })
-- set("n", "[b", "<cmd>bprevious<cr>", { desc = "Prev Buffer" })
-- set("n", "]b", "<cmd>bnext<cr>", { desc = "Next Buffer" })
-- set("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
-- set("n", "<leader>`", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
-- set("n", "<leader>bd", LazyVim.ui.bufremove, { desc = "Delete Buffer" })
-- set("n", "<leader>bD", "<cmd>:bd<cr>", { desc = "Delete Buffer and Window" })
--
-- -- Clear search with <esc>
-- set({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape and Clear hlsearch" })
--
-- -- Clear search, diff update and redraw
-- -- taken from runtime/lua/_editor.lua
-- set(
--   "n",
--   "<leader>ur",
--   "<Cmd>nohlsearch<Bar>diffupdate<Bar>normal! <C-L><CR>",
--   { desc = "Redraw / Clear hlsearch / Diff Update" }
-- )
--
-- -- https://github.com/mhinz/vim-galore#saner-behavior-of-n-and-n
-- set("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, desc = "Next Search Result" })
-- set("x", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
-- set("o", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
-- set("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, desc = "Prev Search Result" })
-- set("x", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
-- set("o", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
--
-- -- Add undo break-points
-- set("i", ",", ",<c-g>u")
-- set("i", ".", ".<c-g>u")
-- set("i", ";", ";<c-g>u")
--
-- -- save file
-- set({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save File" })
--
-- --keywordprg
-- set("n", "<leader>K", "<cmd>norm! K<cr>", { desc = "Keywordprg" })
--
-- -- better indenting
-- set("v", "<", "<gv")
-- set("v", ">", ">gv")
--
-- -- commenting
-- set("n", "gco", "o<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>", { desc = "Add Comment Below" })
-- set("n", "gcO", "O<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>", { desc = "Add Comment Above" })
--
-- -- lazy
-- set("n", "<leader>l", "<cmd>Lazy<cr>", { desc = "Lazy" })
--
-- -- new file
-- set("n", "<leader>fn", "<cmd>enew<cr>", { desc = "New File" })
--
-- set("n", "<leader>xl", "<cmd>lopen<cr>", { desc = "Location List" })
-- set("n", "<leader>xq", "<cmd>copen<cr>", { desc = "Quickfix List" })
--
-- set("n", "[q", vim.cmd.cprev, { desc = "Previous Quickfix" })
-- set("n", "]q", vim.cmd.cnext, { desc = "Next Quickfix" })
--
-- -- formatting
-- set({ "n", "v" }, "<leader>cf", function()
--   LazyVim.format({ force = true })
-- end, { desc = "Format" })
--
-- -- diagnostic
-- local diagnostic_goto = function(next, severity)
--   local go = next and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
--   severity = severity and vim.diagnostic.severity[severity] or nil
--   return function()
--     go({ severity = severity })
--   end
-- end
-- set("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line Diagnostics" })
-- set("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
-- set("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
-- set("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Error" })
-- set("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Error" })
-- set("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Warning" })
-- set("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })
--
-- -- stylua: ignore start
--
-- -- toggle options
-- LazyVim.toggle.set("<leader>uf", LazyVim.toggle.format())
-- LazyVim.toggle.set("<leader>uF", LazyVim.toggle.format(true))
-- LazyVim.toggle.set("<leader>us", LazyVim.toggle("spell", { name = "Spelling" }))
-- LazyVim.toggle.set("<leader>uw", LazyVim.toggle("wrap", { name = "Wrap" }))
-- LazyVim.toggle.set("<leader>uL", LazyVim.toggle("relativenumber", { name = "Relative Number" }))
-- LazyVim.toggle.set("<leader>ud", LazyVim.toggle.diagnostics)
-- LazyVim.toggle.set("<leader>ul", LazyVim.toggle.number)
-- LazyVim.toggle.set( "<leader>uc", LazyVim.toggle("conceallevel", { values = { 0, vim.o.conceallevel > 0 and vim.o.conceallevel or 2 } }))
-- LazyVim.toggle.set("<leader>uT", LazyVim.toggle.treesitter)
-- LazyVim.toggle.set("<leader>ub", LazyVim.toggle("background", { values = { "light", "dark" }, name = "Background" }))
-- if vim.lsp.inlay_hint then
--   LazyVim.toggle.set("<leader>uh", LazyVim.toggle.inlay_hints)
-- end
--
-- -- lazygit
-- set("n", "<leader>gg", function() LazyVim.lazygit( { cwd = LazyVim.root.git() }) end, { desc = "Lazygit (Root Dir)" })
-- set("n", "<leader>gG", function() LazyVim.lazygit() end, { desc = "Lazygit (cwd)" })
-- set("n", "<leader>gb", LazyVim.lazygit.blame_line, { desc = "Git Blame Line" })
-- set("n", "<leader>gB", LazyVim.lazygit.browse, { desc = "Git Browse" })
--
-- set("n", "<leader>gf", function()
--   local git_path = vim.api.nvim_buf_get_name(0)
--   LazyVim.lazygit({args = { "-f", vim.trim(git_path) }})
-- end, { desc = "Lazygit Current File History" })
--
-- set("n", "<leader>gl", function()
--   LazyVim.lazygit({ args = { "log" }, cwd = LazyVim.root.git() })
-- end, { desc = "Lazygit Log" })
-- set("n", "<leader>gL", function()
--   LazyVim.lazygit({ args = { "log" } })
-- end, { desc = "Lazygit Log (cwd)" })
--
-- -- quit
-- set("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit All" })
--
-- -- highlights under cursor
-- set("n", "<leader>ui", vim.show_pos, { desc = "Inspect Pos" })
-- set("n", "<leader>uI", "<cmd>InspectTree<cr>", { desc = "Inspect Tree" })
--
-- -- LazyVim Changelog
-- set("n", "<leader>L", function() LazyVim.news.changelog() end, { desc = "LazyVim Changelog" })
--
-- -- floating terminal
-- local lazyterm = function() LazyVim.terminal(nil, { cwd = LazyVim.root() }) end
-- set("n", "<leader>ft", lazyterm, { desc = "Terminal (Root Dir)" })
-- set("n", "<leader>fT", function() LazyVim.terminal() end, { desc = "Terminal (cwd)" })
-- set("n", "<c-/>", lazyterm, { desc = "Terminal (Root Dir)" })
-- set("n", "<c-_>", lazyterm, { desc = "which_key_ignore" })
--
-- -- Terminal Mappings
-- set("t", "<esc><esc>", "<c-\\><c-n>", { desc = "Enter Normal Mode" })
-- set("t", "<C-h>", "<cmd>wincmd h<cr>", { desc = "Go to Left Window" })
-- set("t", "<C-j>", "<cmd>wincmd j<cr>", { desc = "Go to Lower Window" })
-- set("t", "<C-k>", "<cmd>wincmd k<cr>", { desc = "Go to Upper Window" })
-- set("t", "<C-l>", "<cmd>wincmd l<cr>", { desc = "Go to Right Window" })
-- set("t", "<C-/>", "<cmd>close<cr>", { desc = "Hide Terminal" })
-- set("t", "<c-_>", "<cmd>close<cr>", { desc = "which_key_ignore" })
--
-- -- windows
-- set("n", "<leader>w", "<c-w>", { desc = "Windows", remap = true })
-- set("n", "<leader>-", "<C-W>s", { desc = "Split Window Below", remap = true })
-- set("n", "<leader>|", "<C-W>v", { desc = "Split Window Right", remap = true })
-- set("n", "<leader>wd", "<C-W>c", { desc = "Delete Window", remap = true })
-- LazyVim.toggle.set("<leader>wm", LazyVim.toggle.maximize)
--
-- -- tabs
-- set("n", "<leader><tab>l", "<cmd>tablast<cr>", { desc = "Last Tab" })
-- set("n", "<leader><tab>o", "<cmd>tabonly<cr>", { desc = "Close Other Tabs" })
-- set("n", "<leader><tab>f", "<cmd>tabfirst<cr>", { desc = "First Tab" })
-- set("n", "<leader><tab><tab>", "<cmd>tabnew<cr>", { desc = "New Tab" })
-- set("n", "<leader><tab>]", "<cmd>tabnext<cr>", { desc = "Next Tab" })
-- set("n", "<leader><tab>d", "<cmd>tabclose<cr>", { desc = "Close Tab" })
-- set("n", "<leader><tab>[", "<cmd>tabprevious<cr>", { desc = "Previous Tab" })
